CREATE PROCEDURE AddGeometryColumn (
    IN SPATIAL_SCHEMA VARCHAR(128),
    IN SPATIAL_TABLE VARCHAR(128),
    IN SPATIAL_COLUMN VARCHAR(128),
    IN SPATIAL_SRID INT,
    IN SPATIAL_TYPE VARCHAR(128),
    IN SPATIAL_DIM INT
)
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.AddGeometryColumnProc'
    PARAMETER STYLE JAVA
    MODIFIES SQL DATA;

CREATE PROCEDURE CreateSpatialIndex (
    IN SPATIAL_SCHEMA VARCHAR(128),
    IN SPATIAL_TABLE VARCHAR(128),
    IN SPATIAL_COLUMN VARCHAR(128),
    IN SPATIAL_SRID VARCHAR(16)
)
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.CreateSpatialIndexProc'
    PARAMETER STYLE JAVA
    MODIFIES SQL DATA;

CREATE PROCEDURE DropGeometryColumn (
    IN SPATIAL_SCHEMA VARCHAR(128),
    IN SPATIAL_TABLE VARCHAR(128),
    IN SPATIAL_COLUMN VARCHAR(128)
)
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.DropGeometryColumnProc'
    PARAMETER STYLE JAVA
    MODIFIES SQL DATA;

CREATE PROCEDURE DropGeometryColumns (
    IN SPATIAL_SCHEMA VARCHAR(128),
    IN SPATIAL_TABLE VARCHAR(128)
)
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.DropGeometryColumnsProc'
    PARAMETER STYLE JAVA
    MODIFIES SQL DATA;

CREATE PROCEDURE DropSpatialIndex (
    IN SPATIAL_SCHEMA VARCHAR(128),
    IN SPATIAL_TABLE VARCHAR(128)
)
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.DropSpatialIndexProc'
    PARAMETER STYLE JAVA
    MODIFIES SQL DATA;

CREATE FUNCTION EnvelopeAsText (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS VARCHAR(32672)
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.EnvelopeAsText'
    PARAMETER STYLE JAVA;

CREATE FUNCTION GeometryType (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS VARCHAR(32672)
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.GeometryType'
    PARAMETER STYLE JAVA;

CREATE FUNCTION ST_Area (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS DOUBLE PRECISION
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Area'
    PARAMETER STYLE JAVA
    DETERMINISTIC;

CREATE FUNCTION ST_AsEWKB (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_AsEWKB'
    PARAMETER STYLE JAVA;

CREATE FUNCTION ST_AsEWKT (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS VARCHAR(32672)
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_AsEWKT'
    PARAMETER STYLE JAVA;

CREATE FUNCTION ST_AsHexEWKB (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS VARCHAR(32672)
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_AsHexEWKB'
    PARAMETER STYLE JAVA;

CREATE FUNCTION ST_AsText (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS VARCHAR(32672)
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_AsText'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_AsBinary (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_AsBinary'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_BBox (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA
) RETURNS BOOLEAN
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_BBox'
    PARAMETER STYLE JAVA;

CREATE FUNCTION ST_Boundary (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Boundary'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_Buffer (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA,
    SPATIAL_DISTANCE DOUBLE PRECISION
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Buffer'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_Centroid (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Centroid'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_Crosses (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA
) RETURNS BOOLEAN
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Crosses'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_Contains (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA
) RETURNS BOOLEAN
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Contains'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_ConvexHull (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_ConvexHull'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_DWithin (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA,
    SPATIAL_DISTANCE DOUBLE PRECISION
) RETURNS BOOLEAN
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_DWithin'
    PARAMETER STYLE JAVA;

CREATE FUNCTION ST_Disjoint (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA
) RETURNS BOOLEAN
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Disjoint'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_Distance (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA
) RETURNS DOUBLE PRECISION
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Distance'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_Difference (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Difference'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_Dimension (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS SMALLINT
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Dimension'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_Envelope (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS VARCHAR(32672)
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Envelope'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_Equals (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA
) RETURNS BOOLEAN
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Equals'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_GeoHash (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS VARCHAR(32672)
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_GeoHash'
    PARAMETER STYLE JAVA;

CREATE FUNCTION ST_GeomFromEWKB (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_GeomFromEWKB'
    PARAMETER STYLE JAVA;

CREATE FUNCTION ST_GeomFromEWKT (
    SPATIAL_WKT VARCHAR(32672)
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_GeomFromEWKT'
    PARAMETER STYLE JAVA;

CREATE FUNCTION ST_GeomFromText (
    SPATIAL_WKT VARCHAR(32672),
    SPATIAL_SRID INTEGER
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_GeomFromText'
    PARAMETER STYLE JAVA;

CREATE FUNCTION ST_GeomFromWKB (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA,
    SPATIAL_SRID INTEGER
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_GeomFromWKB'
    PARAMETER STYLE JAVA;

CREATE FUNCTION ST_Intersection (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Intersection'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_Intersects (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA
) RETURNS BOOLEAN
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Intersects'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_IsEmpty (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS BOOLEAN
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_IsEmpty'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_IsSimple (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS BOOLEAN
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_IsSimple'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_IsValid (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS BOOLEAN
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_IsValid'
    PARAMETER STYLE JAVA;

CREATE FUNCTION ST_MakePoint (
    SPATIAL_X DOUBLE PRECISION,
    SPATIAL_Y DOUBLE PRECISION
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_MakePoint'
    PARAMETER STYLE JAVA;

CREATE FUNCTION ST_MakeBox2D (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_MakeBox2D'
    PARAMETER STYLE JAVA;

# Derby doesn't support function overloading.
#CREATE FUNCTION ST_MakeBox2D (
#    SPATIAL_X1 DOUBLE PRECISION,
#    SPATIAL_Y1 DOUBLE PRECISION,
#    SPATIAL_X2 DOUBLE PRECISION,
#    SPATIAL_Y2 DOUBLE PRECISION
#) RETURNS LONG VARCHAR FOR BIT DATA
#    LANGUAGE JAVA
#    EXTERNAL NAME 'geodb.GeoDB.ST_MakeBox2D'
#    PARAMETER STYLE JAVA;

CREATE FUNCTION ST_Overlaps (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA
) RETURNS BOOLEAN
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Overlaps'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_Relate (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA
) RETURNS VARCHAR(32672)
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Relate'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

# Derby doesn't support function overloading.
#CREATE FUNCTION ST_Relate (
#    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
#    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA,
#    SPATIAL_INTERSECTION_PATTERN VARCHAR(32672)
#) RETURNS BOOLEAN
#    LANGUAGE JAVA
#    EXTERNAL NAME 'geodb.GeoDB.ST_Relate'
#    PARAMETER STYLE JAVA
#    DETERMINISTIC
#    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_SRID (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS INT
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_SRID'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_X (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS DOUBLE PRECISION
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_X'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_Y (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA
) RETURNS DOUBLE PRECISION
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Y'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_SetSRID (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA,
    SPATIAL_SRID INT
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_SetSRID'
    PARAMETER STYLE JAVA;

CREATE FUNCTION ST_Simplify (
    SPATIAL_WKB LONG VARCHAR FOR BIT DATA,
    SPATIAL_DISTANCE DOUBLE PRECISION
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Simplify'
    PARAMETER STYLE JAVA;

CREATE FUNCTION ST_SymDifference (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_SymDifference'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_Touches (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA
) RETURNS BOOLEAN
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Touches'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_Union (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA
) RETURNS LONG VARCHAR FOR BIT DATA
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Union'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION ST_Within (
    SPATIAL_WKB1 LONG VARCHAR FOR BIT DATA,
    SPATIAL_WKB2 LONG VARCHAR FOR BIT DATA
) RETURNS BOOLEAN
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.ST_Within'
    PARAMETER STYLE JAVA
    DETERMINISTIC
    RETURNS NULL ON NULL INPUT;

CREATE FUNCTION Version () RETURNS VARCHAR(16)
    LANGUAGE JAVA
    EXTERNAL NAME 'geodb.GeoDB.Version'
    PARAMETER STYLE JAVA;

# Derby can't alias types.
#CREATE DOMAIN POINT AS BLOB
#CREATE DOMAIN LINESTRING AS BLOB
#CREATE DOMAIN POLYGON AS BLOB
#CREATE DOMAIN MULTIPOINT AS BLOB
#CREATE DOMAIN MULTILINESTRING AS BLOB
#CREATE DOMAIN MULTIPOLYGON AS BLOB
#CREATE DOMAIN GEOMETRYCOLLECTION AS BLOB
#CREATE DOMAIN GEOMETRY AS BLOB

CREATE DERBY AGGREGATE ST_Extent
    FOR LONG VARCHAR FOR BIT DATA
    RETURNS LONG VARCHAR FOR BIT DATA
    EXTERNAL NAME 'geodb.aggregate.Extent';

CREATE DERBY AGGREGATE ST_Union_Aggregate
    FOR LONG VARCHAR FOR BIT DATA
    RETURNS LONG VARCHAR FOR BIT DATA
    EXTERNAL NAME 'geodb.aggregate.Union';
